config/routes.rb
Rails.application.routes.draw do
  resources :learnwordlists
  resources :wordlists
  resources :results
  resources :lessons
  resources :categories
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wordlist.rb
class Wordlist < ApplicationRecord
  has_many :learnwordlists, :dependent => :destroy
  belongs_to :category
end

app/controllers/wordlists_controller.rb
class WordlistsController < ApplicationController
  before_action :set_wordlist, only: [:show, :edit, :update, :destroy]

  # GET /wordlists
  # GET /wordlists.json
  def index
    @wordlists = Wordlist.all
  end

  # GET /wordlists/1
  # GET /wordlists/1.json
  def show
  end

  # GET /wordlists/new
  def new
    @wordlist = Wordlist.new
  end

  # GET /wordlists/1/edit
  def edit
  end

  # POST /wordlists
  # POST /wordlists.json
  def create
    @wordlist = Wordlist.new(wordlist_params)

    respond_to do |format|
      if @wordlist.save
        format.html { redirect_to @wordlist, notice: 'Wordlist was successfully created.' }
        format.json { render :show, status: :created, location: @wordlist }
      else
        format.html { render :new }
        format.json { render json: @wordlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wordlists/1
  # PATCH/PUT /wordlists/1.json
  def update
    respond_to do |format|
      if @wordlist.update(wordlist_params)
        format.html { redirect_to @wordlist, notice: 'Wordlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wordlist }
      else
        format.html { render :edit }
        format.json { render json: @wordlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wordlists/1
  # DELETE /wordlists/1.json
  def destroy
    @wordlist.destroy
    respond_to do |format|
      format.html { redirect_to wordlists_url, notice: 'Wordlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wordlist
      @wordlist = Wordlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wordlist_params
      params.require(:wordlist).permit(:wordlist_id, :category_id, :language, :translate_language)
    end
end

app/helpers/wordlists_helper.rb
module WordlistsHelper
end

app/views/wordlists/_form.html.erb
<%= form_with(model: wordlist, local: true) do |form| %>
  <% if wordlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wordlist.errors.count, "error") %> prohibited this wordlist from being saved:</h2>

      <ul>
        <% wordlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wordlist_id %>
    <%= form.number_field :wordlist_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :translate_language %>
    <%= form.text_field :translate_language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wordlists/edit.html.erb
<h1>Editing Wordlist</h1>

<%= render 'form', wordlist: @wordlist %>

<%= link_to 'Show', @wordlist %> |
<%= link_to 'Back', wordlists_path %>

app/views/wordlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wordlists</h1>

<table>
  <thead>
    <tr>
      <th>Wordlist</th>
      <th>Category</th>
      <th>Language</th>
      <th>Translate language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wordlists.each do |wordlist| %>
      <tr>
        <td><%= wordlist.wordlist_id %></td>
        <td><%= wordlist.category_id %></td>
        <td><%= wordlist.language %></td>
        <td><%= wordlist.translate_language %></td>
        <td><%= link_to 'Show', wordlist %></td>
        <td><%= link_to 'Edit', edit_wordlist_path(wordlist) %></td>
        <td><%= link_to 'Destroy', wordlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wordlist', new_wordlist_path %>

app/views/wordlists/new.html.erb
<h1>New Wordlist</h1>

<%= render 'form', wordlist: @wordlist %>

<%= link_to 'Back', wordlists_path %>

app/views/wordlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wordlist:</strong>
  <%= @wordlist.wordlist_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @wordlist.category_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @wordlist.language %>
</p>

<p>
  <strong>Translate language:</strong>
  <%= @wordlist.translate_language %>
</p>

<%= link_to 'Edit', edit_wordlist_path(@wordlist) %> |
<%= link_to 'Back', wordlists_path %>